name = "McSpoil"
author = "StarrFox"
version = "0.4.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "6c48dd9129ea379006933ab703d92c7e925ccd1a5904d4c5747a50fb49bfbb0a"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
