name = "ForgotToSetName"
author = "StarrFox"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "f35151639c1f3ae1bcbeeb8d7696ad808b68ee4689780e776a303dca75f0c3c0"

[versions]
forge = "43.2.21"
minecraft = "1.19.2"
